### PR TITLE
depricated application.langs changed to play.i18nn.langs

### PR DESCRIPTION
**Pull request by Miresnare**

### CODE REVIEW

**Comment by agustafson** [comment]
Hi @Miresnare - it looks like this change breaks things, as `play.i18n.langs` is an array. Docs are at:
https://www.playframework.com/documentation/2.5.x/ScalaI18N
I'll put in a PR to fix.

**Comment by Miresnare** [comment]
play.i18n.langs="en" in frontend-bootstrap works locally fine for me. No warnings, compiles fine and all tests pass.

You are correct that it's an array, I have to override in pertax-frontend with play.i18n.langs=["en","cy"] over the previously used application.langs="en,cy"

**Comment by agustafson** [comment]
The frontend tests were all passing up to that point because the config wasn't being parsed and then used to pull out `Langs`. And the problem occurred in an app which uses frontend-bootstrap. I've added a test which fails if the `langs` aren't an array in #50

**Comment by Miresnare** [comment]
Ah, right. Nice one.

**Pull request merged**
